# Inserts a blank line between shell prompts
add_newline = true

# Global format
format = """${time}${all}${line_break}\
${custom.history}${jobs}${status}${shell}${character}"""

# Local time
[time]
disabled = false
format = "[$time│ ](bold black)"
time_format = "%H:%M"

# Git
[git_branch]
symbol = "⌥ "

[git_status]
format = '[$all_status$ahead_behind]($style)'
style = "bold yellow"
ahead = "▲"
behind = "▼"
diverged = "◆"
untracked = "◯"
modified = "⨀"
renamed = "◎"
staged = "●"
deleted = "◌"
stashed = "*"

# Languages
[python]
style = "bold green"

# Input line
[custom.history]
description = "Show current line number in history"
command = "echo '\\!'"
when = "true"
style = "black"
format = "[ $output]($style)[╰╴](bold black)"

[character]
success_symbol = "[❯](bold white)"
error_symbol = "[❯](bold red)"

# Disabled modules
[battery]
disabled = true

[cmd_duration]
disabled = true
