# Inserts a blank line between shell prompts
add_newline = true

# Git
[git_branch]
symbol = "⌥ "

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "bold yellow"
ahead = "▲"
behind = "▼"
diverged = "◆"
untracked = "◯"
modified = "⨀"
renamed = "◎"
staged = "●"
deleted = "◌"
stashed = "*"

# Disabled modules
[battery]
disabled = true

[cmd_duration]
disabled = true
