# Global format
format = """${custom.history}${all}${line_break}\
${time}${jobs}${status}${shell}${character}"""

# Inserts a blank line between shell prompts
add_newline = true

# Increase execution timeout (git can take some time to finish) 
command_timeout = 1000

# Command history number
[custom.history]
description = "Show current command number in history"
command = "echo '\\!\\033[7G'"  # print number and move cursor to column 7
when = "true"
style = "bold black"
format = "[$output]($style)[╷ ](bold black)"

# User location
[hostname]
format = "[$hostname]($style):"

# Git
[git_branch]
symbol = "⌥ "

[git_status]
ignore_submodules = true
format = '[$all_status$ahead_behind ]($style)'
style = "bold yellow"
ahead = "▲"
behind = "▼"
diverged = "◆"
untracked = "◯"
modified = "⨀"
renamed = "◎"
staged = "●"
deleted = "◌"
stashed = "*"

# Languages
[python]
style = "bold green"

[rlang]
detect_files = []
symbol = "ℝ "

[ruby]
symbol = "⬘ "

# Input line
[time]
disabled = false
time_format = "%H:%M"
style = "black"
format = "[$time]($style)[ ╰╴](bold black)"

[jobs]
symbol = "⚙"
number_threshold = 1

[character]
success_symbol = "[❯](bold white)"
error_symbol = "[✖](bold red)"

# Disabled modules
[battery]
disabled = true

[cmd_duration]
disabled = true
